packages:
  - apps/api
  - apps/web-app
  - apps/mobile
  - apps/reverse-proxy
  - packages/config-eslint
  - packages/email-templates
  - packages/shared
  - packages/typescript-config

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - cpu-features
  - esbuild
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  next@>=15.5.0-canary.0 <15.5.7: '>=15.5.7'
  next@>=15.5.1-canary.0 <15.5.8: '>=15.5.8'
