packages:
  - apps/api
  - apps/web-app
  - apps/reverse-proxy
  - packages/config-eslint
  - packages/email-templates
  - packages/shared
  - packages/typescript-config

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - cpu-features
  - esbuild
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
